STANDARD_CAPABILITIES = {
    "target_temperature": {
        "kind": "property",
        "aliases": ["target-temperature", "target_temperature", "target-temp", "ac-target-temperature"],
        "label": "Target Temperature",
        "value_type": "integer",
        "value_resolution": ["range", "enum", "integer"],
        "intent_keywords": ["温度"],
        "intent_strip_keywords": ["温度"],
        "intent_requires_number": True,
        "intent_priority": 30,
        "preferred_tool": "set_target_temperature",
        "families": ["target_temperature"],
        "domains": ["climate"],
        "supported_device_types": ["air-conditioner", "air-condition-outlet", "heater", "bath-heater", "thermostat"],
        "description": "Target temperature capability with device-provided range metadata when available.",
    },
    "mode": {
        "kind": "property",
        "aliases": ["mode", "air-conditioner-mode", "air_conditioner_mode", "ac-mode"],
        "label": "Mode",
        "value_type": "string",
        "value_resolution": ["enum", "string"],
        "intent_keywords": ["模式"],
        "intent_strip_keywords": ["模式"],
        "intent_pattern": r"(制冷|制热|送风|除湿|自动|auto|cool|heat|dry|fan)",
        "intent_priority": 50,
        "preferred_tool": "set_hvac_mode",
        "families": ["mode"],
        "domains": ["climate"],
        "supported_device_types": ["air-conditioner", "air-condition-outlet", "heater", "bath-heater", "thermostat", "fan", "air-purifier"],
        "description": "Mode capability with device-provided enum metadata when available.",
    },
    "fan_speed": {
        "kind": "property",
        "aliases": ["fan-level", "fan_level", "speed-level", "speed_level", "wind-speed", "wind_speed"],
        "label": "Fan Speed",
        "value_type": "integer",
        "value_resolution": ["enum", "range", "integer"],
        "intent_keywords": ["风速", "风量", "档位"],
        "intent_strip_keywords": ["风速", "风量", "档位"],
        "intent_priority": 35,
        "preferred_tool": "set_fan_speed",
        "families": ["fan_speed"],
        "domains": ["airflow"],
        "supported_device_types": ["fan", "air-conditioner", "air-condition-outlet", "air-purifier", "bath-heater"],
        "description": "Fan speed capability with device-provided enum or range metadata when available.",
    },
}

STANDARD_OPERATION_CAPABILITY_MAP = {
    "set_target_temperature": "target_temperature",
    "set_hvac_mode": "mode",
    "set_fan_speed": "fan_speed",
}
