#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"
WEB_ENV_FILE="$(cd "$(dirname "$0")" && pwd)/packages/web-next/.env.local"
DOMAIN="${SYNAPSE_PUBLIC_DOMAIN:-change-me.example.com}"
APP_URL="https://$DOMAIN"
API_PROXY_ORIGIN="${SYNAPSE_API_PROXY_ORIGIN:-http://localhost:3001}"

generate_password() {
  openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

ROOT_ENV_CREATED=false
WEB_ENV_CREATED=false

if [ ! -f "$ENV_FILE" ]; then
  POSTGRES_PASSWORD=$(generate_password)
  REDIS_PASSWORD=$(generate_password)
  JWT_SECRET=$(generate_password)
  JWT_REFRESH_SECRET=$(generate_password)
  APP_SECRET=$(generate_password)
  MCP_ENCRYPTION_KEY=$(generate_password)
  SPICEDB_TOKEN=$(generate_password)

  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Do NOT commit this file to git.

# PostgreSQL
POSTGRES_USER=synapse
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=synapse

# Redis
REDIS_PASSWORD=$REDIS_PASSWORD

# JWT / application secrets
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
APP_SECRET=$APP_SECRET
MCP_ENCRYPTION_KEY=$MCP_ENCRYPTION_KEY

# Application URLs
APP_BASE_URL=$APP_URL
NEXT_PUBLIC_APP_URL=$APP_URL
NEXT_PUBLIC_SITE_URL=$APP_URL

# Application runtime
PORT=3001
HOST=localhost
DATABASE_URL=postgresql://synapse:${POSTGRES_PASSWORD}@localhost:5432/synapse
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379
AUTHZ_ENABLED=true
SPICEDB_ENDPOINT=localhost:50051
SPICEDB_TOKEN=$SPICEDB_TOKEN
SPICEDB_INSECURE=true
SPICEDB_SCHEMA_PATH=docs/spicedb-schema.zed
PLATFORM_ADMIN_EMAILS=demo@synapse.dev

# Frontend runtime
NEXT_PUBLIC_API_URL=/api/v1
NEXT_PUBLIC_WS_URL=wss://$DOMAIN

# AI provider
AI_PROVIDER=anthropic
AI_API_KEY=
AI_BASE_URL=
AI_MODEL=
ANTHROPIC_API_KEY=
ANTHROPIC_BASE_URL=
EOF

  chmod 600 "$ENV_FILE"
  ROOT_ENV_CREATED=true
  echo "Generated root env at $ENV_FILE"
else
  echo ".env already exists at $ENV_FILE"
fi

if [ ! -f "$WEB_ENV_FILE" ]; then
  mkdir -p "$(dirname "$WEB_ENV_FILE")"
  cat > "$WEB_ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
NEXT_PUBLIC_API_URL=/api/v1
NEXT_PUBLIC_WS_URL=wss://$DOMAIN
NEXT_PUBLIC_APP_URL=$APP_URL
NEXT_PUBLIC_SITE_URL=$APP_URL
API_PROXY_ORIGIN=$API_PROXY_ORIGIN
EOF

  chmod 600 "$WEB_ENV_FILE"
  WEB_ENV_CREATED=true
  echo "Generated web env at $WEB_ENV_FILE"
else
  echo "Web env already exists at $WEB_ENV_FILE"
fi

if [ "$ROOT_ENV_CREATED" = false ] && [ "$WEB_ENV_CREATED" = false ]; then
  echo "No env files were created."
  exit 0
fi

echo "Local secrets and URLs have been initialized."
echo ""
echo "Next steps:"
echo "  1. Install docker + nginx on the host if they are missing"
echo "  2. Run: sudo docker compose up -d postgres redis spicedb-migrate spicedb"
echo "  3. Run: npm ci"
echo "  4. Run: npm run db:migrate -w packages/api"
echo "  5. Enable services: sudo systemctl enable --now synapse-api synapse-web-dev"
