#!/usr/bin/env bash
# Build-time generator for RFC 9842 Compression Dictionary Transport (CDT) +
# plain precompressed variants for Next.js /_next/static assets.
#
# Runs INSIDE the nginx image build (never a manual step) against the web build's
# .next/static, and emits, next to each .js/.css:
#   - .br  / .zst / .gz   plain precompressed (served by *_static to all clients)
#   - .dcb / .dcz         RFC 9842 dictionary-compressed deltas (Chromium 130+)
# plus a shared dictionary file and a generated nginx map snippet.
#
# Verified framing (RFC 9842 S4/S5):
#   dcb = 0xFF 'D' 'C' 'B'                       (4 bytes) + raw SHA-256(dict) (32) + shared-brotli(-D dict) stream
#   dcz = 0x5E2A4D18 20000000 (zstd skippable)   (8 bytes) + raw SHA-256(dict) (32) + zstd(-D dict) stream
# Negotiation is map-based (no njs): ONE shared dictionary => ONE known SHA-256,
# matched literally against the Available-Dictionary request header.
set -euo pipefail

WEB_ROOT="${1:?usage: gen-cdt.sh <web-root-dir> <map-out.conf>}"   # contains _next/static
MAP_OUT="${2:?usage: gen-cdt.sh <web-root-dir> <map-out.conf>}"
STATIC_DIR="$WEB_ROOT/_next/static"
DICT_DIR="$WEB_ROOT/_next/cdt-dict"
DICT_BUDGET_BYTES="${CDT_DICT_BUDGET_BYTES:-1048576}"   # ~1MB shared dictionary cap

# Always-valid map so $cdt_dict_ok / $cdt_dict_url are defined even when CDT is
# disabled (an undefined nginx variable is a hard config error).
write_disabled_map() {
  {
    echo "# CDT disabled (no static assets to delta-compress)."
    echo 'map $http_available_dictionary $cdt_dict_ok { default 0; }'
    echo 'map $host $cdt_dict_url { default ""; }'
  } > "$MAP_OUT"
}

if [ ! -d "$STATIC_DIR" ]; then
  echo "gen-cdt: no $STATIC_DIR — emitting disabled-CDT map" >&2
  write_disabled_map
  exit 0
fi

mkdir -p "$DICT_DIR"

# 1) Shared dictionary = the largest JS chunks (the stable, widely-shared code a
#    returning visitor most likely already holds), concatenated up to the budget.
tmp_dict="$(mktemp)"
acc=0
while IFS=$'\t' read -r sz path; do
  if [ $((acc + sz)) -gt "$DICT_BUDGET_BYTES" ]; then continue; fi
  cat "$path" >> "$tmp_dict"
  acc=$((acc + sz))
done < <(find "$STATIC_DIR" -type f -name '*.js' -printf '%s\t%p\n' | sort -rn)
# Fallback: if no JS matched, use whatever js/css exists.
if [ ! -s "$tmp_dict" ]; then
  find "$STATIC_DIR" -type f \( -name '*.js' -o -name '*.css' \) -exec cat {} + >> "$tmp_dict" || true
fi
if [ ! -s "$tmp_dict" ]; then
  echo "gen-cdt: no js/css assets — emitting disabled-CDT map" >&2
  write_disabled_map; rm -f "$tmp_dict"; exit 0
fi

# 2) Hash (raw 32 bytes for the dcb/dcz frame; base64 for the Available-Dictionary match).
hash_bin="$(mktemp)"
openssl dgst -sha256 -binary "$tmp_dict" > "$hash_bin"
hash_hex="$(openssl dgst -sha256 "$tmp_dict" | awk '{print $NF}')"
hash_b64="$(openssl base64 -A < "$hash_bin")"

# 3) Content-address the dictionary file so its URL is stable + immutable-cacheable.
dict_file="$DICT_DIR/$hash_hex.dat"
mv "$tmp_dict" "$dict_file"
dict_url="/_next/cdt-dict/$hash_hex.dat"
# Precompress the dictionary so the one-time ~1MB fetch ships small (served via
# *_static). The browser decompresses to the raw bytes, whose SHA-256 is what
# the dcb/dcz frames reference — so transport encoding is transparent.
brotli -q 11 -c "$dict_file" > "$dict_file.br"
zstd -19 -q -c "$dict_file" > "$dict_file.zst"
gzip -9 -c "$dict_file" > "$dict_file.gz"

DCB_MAGIC=$'\xff\x44\x43\x42'                       # 0xFF 'D' 'C' 'B'
DCZ_MAGIC=$'\x5e\x2a\x4d\x18\x20\x00\x00\x00'       # zstd skippable frame, 32-byte payload

n=0
while IFS= read -r -d '' f; do
  # Plain precompressed fallbacks (served by brotli_static/zstd_static/gzip_static).
  brotli -q 11 -c "$f" > "$f.br"
  zstd -19 -q -c "$f" > "$f.zst"
  gzip -9 -c "$f" > "$f.gz"
  # RFC 9842 deltas (magic + raw sha256 + dictionary-compressed stream).
  { printf '%s' "$DCB_MAGIC"; cat "$hash_bin"; brotli -q 11 -w 24 -c -D "$dict_file" "$f"; } > "$f.dcb"
  { printf '%s' "$DCZ_MAGIC"; cat "$hash_bin"; zstd -19 -q -D "$dict_file" -c "$f"; } > "$f.dcz"
  n=$((n + 1))
done < <(find "$STATIC_DIR" -type f \( -name '*.js' -o -name '*.css' \) -print0)

rm -f "$hash_bin"

# 4) Generated nginx snippet (included at http context). Exposes:
#    $cdt_dict_ok  = 1 when the client advertises THIS dictionary (exact match on
#                    the literal Available-Dictionary structured-field value).
#    $cdt_dict_url = the dictionary URL (constant), for the Link + Use-As-Dictionary.
{
  echo "# Generated by gen-cdt.sh — DO NOT EDIT. dict=$hash_hex.dat (${acc} bytes), variants=$n"
  echo "map \$http_available_dictionary \$cdt_dict_ok {"
  echo "    default 0;"
  echo "    \":${hash_b64}:\" 1;"
  echo "}"
  echo "map \$host \$cdt_dict_url {"
  echo "    default \"${dict_url}\";"
  echo "}"
} > "$MAP_OUT"

echo "gen-cdt: dictionary=$hash_hex.dat (${acc} bytes), generated .br/.zst/.gz/.dcb/.dcz for $n assets" >&2
