# Synapse one-click installer (Windows / PowerShell).
#
# WHAT: bootstraps a Node.js runtime satisfying @synapse engines, installs
#       @synapse/device-runtime or @synapse/remote-agent-daemon from the
#       private registry, then pairs the device / starts the daemon.
# WHY:  the @synapse npm packages need Node + a configured @synapse:registry
#       before they can run; this supplies that bootstrap step.
#
# Canonical source. The API serves it at GET /api/v1/install.ps1 after
# substituting the @@SYNAPSE_*@@ placeholders. The Node sha256 manifest in the
# SYNAPSE_NODE_MANIFEST block is generated by
# scripts/installer/generate-node-manifest.mjs (shared with install.sh).
#
# SECURITY: Node zip is downloaded to a file (never iex'd) and verified against
# the embedded sha256 before extraction. User PATH is persisted via
# [Environment]::SetEnvironmentVariable(...,'User') — NOT setx (which truncates).

[CmdletBinding()]
param(
  [ValidateSet('device', 'daemon')]
  [string]$Target,
  [string]$Server,
  [string]$Code,
  [string]$ApiKey,
  [ValidateSet('cn', 'intl')]
  [string]$Region,
  [string]$Mirror,
  [string]$ToolchainMirror,
  [switch]$NoModifyPath,
  [switch]$WriteUserNpmrc,
  [switch]$PreferPrivateCache,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
# Windows PowerShell 5.1 defaults to TLS1.0; force TLS1.2 before any web call.
if ($PSVersionTable.PSVersion.Major -lt 6) {
  try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}
}

# --- server-rendered placeholders ------------------------------------------
# The API route replaces each @@...@@ token with a fully PowerShell-quoted
# literal (e.g. 'https://host/'), so do NOT add surrounding quotes here.
$RenderedServerUrl = @@SYNAPSE_SERVER_URL@@
$RenderedPrivateRegistry = @@SYNAPSE_NPM_REGISTRY@@

# >>> SYNAPSE_NODE_MANIFEST (generated — do not edit by hand) >>>
$InstallerNodeVersion = '24.16.0'
$NodeArtifactSha256 = @{
  'linux-x64' = '2faf6a387e9b62b888e21c54f01249fb27537ffecf1842f29f4c919d0a59a0ff'
  'linux-arm64' = '589f5b6dd4fcfee4dfda73013903c966abaa8abd93dbc9d436544e472b4f0e74'
  'darwin-x64' = '298b4c7b3cb80765c8703e42b90324a4ece3b6634947b89e769c3c980ab55185'
  'darwin-arm64' = '39189dab4eeb15706c424af0ac08a3044c9e48f7db12a7d77f6b7aafc7dd5df6'
  'win-x64' = 'edaca9bd58ec8e92037dac4e877d52f6b8f430b81c18b57e264b4e2fb111cd56'
  'win-arm64' = '14834611d4c6b3c06054e7007732b90474c16e0b32f395e05b55a571ef71c6d2'
}
# <<< SYNAPSE_NODE_MANIFEST <<<

# --- mirror tables (shared semantics with install.sh) ----------------------
$MirrorBase = @{
  'ustc' = 'https://mirrors.ustc.edu.cn/node/'
  'huawei' = 'https://mirrors.huaweicloud.com/nodejs/'
  'tencent' = 'https://mirrors.cloud.tencent.com/nodejs-release/'
  'aliyun' = 'https://mirrors.aliyun.com/nodejs-release/'
  'npmmirror' = 'https://cdn.npmmirror.com/binaries/node/'
  'nodejs' = 'https://nodejs.org/dist/'
}
$P5MirrorKeys = @('ustc', 'huawei', 'tencent', 'aliyun', 'npmmirror')

function Write-Log { param($m) [Console]::Error.WriteLine("[synapse-install] $m") }
function Write-WarnLog { param($m) [Console]::Error.WriteLine("[synapse-install] WARN: $m") }
function Die { param($m) [Console]::Error.WriteLine("[synapse-install] ERROR: $m"); exit 1 }

# Dry-run wrapper: print instead of execute. Used for state-changing ops.
function Invoke-Step {
  param([string]$Desc, [scriptblock]$Action)
  if ($DryRun) { Write-Output "DRYRUN: $Desc"; return }
  & $Action
}

function Get-Platform {
  # Real OS arch even from a 32-bit host: PROCESSOR_ARCHITEW6432 first.
  $arch = $env:PROCESSOR_ARCHITEW6432
  if (-not $arch) { $arch = $env:PROCESSOR_ARCHITECTURE }
  switch ($arch) {
    'AMD64' { return 'win-x64' }
    'ARM64' { return 'win-arm64' }
    'x86' { return 'win-x64' }  # 32-bit host on 64-bit OS reports x86; use x64 build
    default { Die "unsupported Windows architecture: $arch" }
  }
}

function Test-NodeEngines {
  # ^20.19.0 || ^22.12.0 || >=23
  param([string]$Version)
  $v = $Version.TrimStart('v')
  $parts = $v.Split('.')
  if ($parts.Count -lt 3) { return $false }
  $maj = 0; $min = 0; $pat = 0
  if (-not [int]::TryParse($parts[0], [ref]$maj)) { return $false }
  if (-not [int]::TryParse($parts[1], [ref]$min)) { return $false }
  if (-not [int]::TryParse($parts[2], [ref]$pat)) { return $false }
  if ($maj -ge 23) { return $true }
  if ($maj -eq 22 -and $min -ge 12) { return $true }
  if ($maj -eq 20 -and ($min -gt 19 -or ($min -eq 19 -and $pat -ge 0))) { return $true }
  return $false
}

function Measure-TlsMs {
  param([string]$Url)
  try {
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    Invoke-WebRequest -Uri $Url -Method Head -TimeoutSec 4 -UseBasicParsing -DisableKeepAlive | Out-Null
    $sw.Stop()
    return [int]$sw.Elapsed.TotalMilliseconds
  } catch { return -1 }
}

function Get-Region {
  if ($Region) { Write-Log "region: $Region (explicit)"; return $Region }
  $cn = Measure-TlsMs 'https://registry.npmmirror.com/'
  $intl = Measure-TlsMs 'https://registry.npmjs.org/'
  if ($cn -ge 0 -and $intl -lt 0) { Write-Log 'region: cn (intl unreachable)'; return 'cn' }
  if ($cn -ge 0 -and $intl -ge 0) {
    if (($cn * 3) -le ($intl * 2)) { Write-Log "region: cn (race ${cn}ms vs ${intl}ms)"; return 'cn' }
    Write-Log "region: intl (race ${cn}ms vs ${intl}ms)"; return 'intl'
  }
  $tz = try { (Get-TimeZone).Id } catch { '' }
  if ($tz -eq 'China Standard Time') { Write-Log 'region: cn (timezone tiebreak)'; return 'cn' }
  Write-Log 'region: intl (default)'
  return 'intl'
}

# Two-stage resolution mirroring Bash resolve_toolchain_mirror.
# Returns @{ NodeBase; NodeKey; P5 } — NodeKey '' for custom URL / official.
function Resolve-ToolchainMirror {
  param([string]$RegionResolved)
  $nodeChoice = $null; $source = 'default'
  if ($Mirror) { $nodeChoice = $Mirror; $source = 'flag' }
  elseif ($env:SYNAPSE_NODE_MIRROR) { $nodeChoice = $env:SYNAPSE_NODE_MIRROR; $source = 'env' }
  elseif ($RegionResolved -eq 'cn') { $nodeChoice = 'ustc'; $source = 'geo' }
  else { $nodeChoice = 'nodejs'; $source = 'default' }

  $nodeBase = $null; $nodeKey = ''
  if ($nodeChoice -match '^https?://') {
    $nodeBase = ($nodeChoice.TrimEnd('/') + '/'); $nodeKey = ''
  }
  elseif ($MirrorBase.ContainsKey($nodeChoice)) {
    $nodeBase = $MirrorBase[$nodeChoice]
    $nodeKey = if ($nodeChoice -eq 'nodejs') { '' } else { $nodeChoice }
  }
  else {
    if ($source -eq 'flag') {
      Die "--mirror/-Mirror: unknown key '$nodeChoice' (use ustc|huawei|tencent|aliyun|npmmirror|nodejs or an https:// URL)"
    }
    Write-WarnLog "ignoring invalid mirror '$nodeChoice' (from $source); using official nodejs.org"
    $nodeBase = $MirrorBase['nodejs']; $nodeKey = ''
  }

  $p5 = ''
  if ($ToolchainMirror) {
    if ($P5MirrorKeys -contains $ToolchainMirror) { $p5 = $ToolchainMirror }
    else { Die "-ToolchainMirror: must be one of $($P5MirrorKeys -join '|') (got '$ToolchainMirror'); custom URLs not allowed for the device toolchain" }
  }
  elseif ($env:SYNAPSE_DEVICE_TOOLCHAIN_MIRROR) {
    if ($P5MirrorKeys -contains $env:SYNAPSE_DEVICE_TOOLCHAIN_MIRROR) { $p5 = $env:SYNAPSE_DEVICE_TOOLCHAIN_MIRROR }
    else { Write-WarnLog "ignoring invalid SYNAPSE_DEVICE_TOOLCHAIN_MIRROR='$($env:SYNAPSE_DEVICE_TOOLCHAIN_MIRROR)'; device toolchain will use official source" }
  }
  elseif ($nodeKey -and ($P5MirrorKeys -contains $nodeKey)) {
    $p5 = $nodeKey
  }
  Write-Log "node mirror: $nodeBase (key='$(if($nodeKey){$nodeKey}else{'custom/official'})'); p5 toolchain mirror: '$(if($p5){$p5}else{'official'})'"
  return @{ NodeBase = $nodeBase; NodeKey = $nodeKey; P5 = $p5 }
}

function Get-FileSha256 { param([string]$Path) (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLower() }

function Save-File {
  param([string]$Url, [string]$OutFile)
  for ($attempt = 1; $attempt -le 3; $attempt++) {
    try {
      Invoke-WebRequest -Uri $Url -OutFile $OutFile -MaximumRedirection 5 -UseBasicParsing
      if ((Get-Item -LiteralPath $OutFile).Length -gt 0) { return }
    } catch {
      Write-WarnLog "download attempt $attempt failed: $($_.Exception.Message)"
      if ($attempt -lt 3) { Start-Sleep -Seconds (2 * $attempt) }
    }
  }
  Die "download failed: $Url"
}

function Test-MirrorHasVersion {
  param([string]$Base)
  try {
    Invoke-WebRequest -Uri "$Base$('v' + $InstallerNodeVersion)/SHASUMS256.txt" -Method Head -TimeoutSec 8 -UseBasicParsing | Out-Null
    return $true
  } catch { return $false }
}

function Select-Mirror {
  param([string]$PreferredBase, [string]$RegionResolved)
  $candidates = @($PreferredBase)
  if ($RegionResolved -eq 'cn') {
    $candidates += @($MirrorBase['ustc'], $MirrorBase['tencent'], $MirrorBase['huawei'], $MirrorBase['aliyun'], $MirrorBase['npmmirror'], $MirrorBase['nodejs'])
  } else {
    $candidates += @($MirrorBase['nodejs'])
  }
  foreach ($b in ($candidates | Select-Object -Unique)) {
    if (Test-MirrorHasVersion $b) { return $b }
    Write-WarnLog "mirror $b unreachable or missing v$InstallerNodeVersion; trying next"
  }
  Die "no reachable mirror for Node $InstallerNodeVersion"
}

function Get-SynapseHome {
  if ($env:SYNAPSE_HOME) { return $env:SYNAPSE_HOME }
  return (Join-Path $env:LOCALAPPDATA 'synapse')
}

$script:NodeExe = $null
$script:NodeDir = $null
$script:NpmCmd = $null
$script:NpmGlobalPrefix = $null

function Initialize-NodeFromPrefix {
  param([string]$Prefix)
  # Windows Node zip lays node.exe at the prefix ROOT (not bin/).
  $script:NodeExe = Join-Path $Prefix 'node.exe'
  $script:NodeDir = $Prefix
  $script:NpmCmd = Join-Path $Prefix 'npm.cmd'
  # Put node + the managed npm-global on PATH for THIS process.
  $env:PATH = "$Prefix;$($script:NpmGlobalPrefix);$env:PATH"
}

function Install-Node {
  param([string]$ArtifactKey, [hashtable]$MirrorInfo, [string]$RegionResolved, [string]$SynapseHome)
  $prefix = Join-Path (Join-Path $SynapseHome 'node') $InstallerNodeVersion

  if ((Test-Path (Join-Path $prefix 'node.exe'))) {
    Write-Log "Node $InstallerNodeVersion already bootstrapped at $prefix"
    Initialize-NodeFromPrefix $prefix
    return
  }

  $expected = $NodeArtifactSha256[$ArtifactKey]
  if (-not $expected) { Die "no embedded sha256 for $ArtifactKey at Node $InstallerNodeVersion" }

  $file = "node-v$InstallerNodeVersion-$ArtifactKey.zip"
  $base = Select-Mirror $MirrorInfo.NodeBase $RegionResolved
  $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + '.zip')
  Write-Log "downloading $file from $base"
  Invoke-Step "download $base$('v' + $InstallerNodeVersion)/$file -> $tmp" {
    Save-File "$base$('v' + $InstallerNodeVersion)/$file" $tmp
    $got = Get-FileSha256 $tmp
    if ($got -ne $expected) { Die "Node sha256 mismatch for $file (expected $expected, got $got)" }
    Write-Log 'sha256 verified'
    $extractParent = Split-Path $prefix -Parent
    New-Item -ItemType Directory -Force -Path $extractParent | Out-Null
    $tmpExtract = Join-Path $extractParent ".extract-$InstallerNodeVersion"
    if (Test-Path $tmpExtract) { Remove-Item -Recurse -Force $tmpExtract }
    Expand-Archive -LiteralPath $tmp -DestinationPath $tmpExtract -Force
    # zip contains a single node-vX-win-arch/ dir; move it to $prefix.
    $inner = Get-ChildItem -Directory $tmpExtract | Select-Object -First 1
    if (Test-Path $prefix) { Remove-Item -Recurse -Force $prefix }
    Move-Item $inner.FullName $prefix
    Remove-Item -Recurse -Force $tmpExtract -ErrorAction SilentlyContinue
    Remove-Item -Force $tmp -ErrorAction SilentlyContinue
  }
  Initialize-NodeFromPrefix $prefix
}

function Set-UserPath {
  param([string]$Dir)
  if ($NoModifyPath) {
    Write-Log "--no-modify-path set: add this to your User PATH manually: $Dir"
    return
  }
  # Read the unexpanded User Path, append if absent, write back (REG via API,
  # never setx). 'User' target needs no admin.
  $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
  if (-not $userPath) { $userPath = '' }
  if (($userPath -split ';') -notcontains $Dir) {
    $newPath = if ($userPath.TrimEnd(';')) { $userPath.TrimEnd(';') + ';' + $Dir } else { $Dir }
    Invoke-Step "persist User PATH += $Dir" {
      [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    }
    Write-Log "added $Dir to User PATH (open a new terminal to pick it up)"
  }
}

function Set-Npmrc {
  param([string]$PrivateRegistry, [string]$ThirdParty, [string]$ManagedNpmrc)
  $lines = @("@synapse:registry=$PrivateRegistry")
  if ($ThirdParty) { $lines += "registry=$ThirdParty" }
  Invoke-Step "write $ManagedNpmrc (@synapse:registry=$PrivateRegistry; registry=$(if($ThirdParty){$ThirdParty}else{'<default>'}))" {
    New-Item -ItemType Directory -Force -Path (Split-Path $ManagedNpmrc -Parent) | Out-Null
    Set-Content -LiteralPath $ManagedNpmrc -Value $lines -Encoding ASCII
  }
  if ($WriteUserNpmrc -and -not $NoModifyPath) {
    $userNpmrc = Join-Path $env:USERPROFILE '.npmrc'
    Invoke-Step "write $userNpmrc" {
      Set-Content -LiteralPath $userNpmrc -Value $lines -Encoding ASCII
    }
  } elseif ($WriteUserNpmrc -and $NoModifyPath) {
    Write-Log "--no-modify-path set: skipping ~/.npmrc; add manually: @synapse:registry=$PrivateRegistry"
  }
}

function Set-ToolchainMirror {
  param([string]$P5)
  if (-not $P5) { return }
  $env:SYNAPSE_DEVICE_TOOLCHAIN_MIRROR = $P5
  Write-Log "device toolchain mirror: $P5 (this process)"
  if ($NoModifyPath) {
    Write-Log "--no-modify-path set: not persisting; set manually: setx SYNAPSE_DEVICE_TOOLCHAIN_MIRROR $P5"
    return
  }
  Invoke-Step "persist User env SYNAPSE_DEVICE_TOOLCHAIN_MIRROR=$P5" {
    [Environment]::SetEnvironmentVariable('SYNAPSE_DEVICE_TOOLCHAIN_MIRROR', $P5, 'User')
  }
}

function Install-SynapsePackage {
  param([string]$Pkg, [string]$PrivateRegistry, [string]$ThirdParty, [string]$ManagedNpmrc)
  $thirdReg = if ($ThirdParty) { $ThirdParty } else { 'https://registry.npmjs.org/' }
  Write-Log "installing $Pkg into $($script:NpmGlobalPrefix)"
  Invoke-Step "npm install -g $Pkg (registry=$thirdReg, @synapse:registry=$PrivateRegistry)" {
    & $script:NpmCmd install --global --prefix $script:NpmGlobalPrefix `
      --userconfig $ManagedNpmrc `
      "--registry=$thirdReg" "--@synapse:registry=$PrivateRegistry" $Pkg
    if ($LASTEXITCODE -ne 0) { Die "npm install $Pkg failed" }
  }
}

function Invoke-Pair {
  param([string]$Bin, [string]$ServerUrl, [string]$PairingCode)
  if (-not $PairingCode) {
    Write-Log "device-runtime installed. To pair: & '$Bin' pair --server '$ServerUrl' --code <pairing-code>"
    return
  }
  if (-not $ServerUrl) { Die '--code given but --server missing; cannot auto-pair' }
  Write-Log 'pairing device...'
  Invoke-Step "$Bin pair --server $ServerUrl --code $PairingCode" {
    & $Bin pair --server $ServerUrl --code $PairingCode
    if ($LASTEXITCODE -ne 0) { Write-WarnLog "auto-pair failed; run manually: & '$Bin' pair --server '$ServerUrl' --code '$PairingCode'" }
  }
}

function Start-Daemon {
  param([string]$Bin, [string]$ServerUrl, [string]$Key)
  if (-not $ServerUrl -or -not $Key) {
    Write-Log "remote-agent-daemon installed. To start: & '$Bin' --server-url '$ServerUrl' --api-key '<api-key>'"
    return
  }
  Write-Log 'starting remote-agent-daemon in this terminal (foreground; Ctrl-C to stop)...'
  Invoke-Step "$Bin --server-url $ServerUrl --api-key <hidden>" {
    & $Bin --server-url $ServerUrl --api-key $Key
    if ($LASTEXITCODE -ne 0) { Write-WarnLog "daemon exited/failed; run manually: & '$Bin' --server-url '$ServerUrl' --api-key '$Key'" }
  }
}

function Main {
  if (-not $Target) { Die '-Target <device|daemon> is required' }

  $server = if ($Server) { $Server } elseif ($env:SYNAPSE_SERVER_ORIGIN) { $env:SYNAPSE_SERVER_ORIGIN } else { $RenderedServerUrl }
  if ($server -like '@@*@@') { $server = '' }
  $privateRegistry = if ($env:SYNAPSE_PRIVATE_NPM_REGISTRY) { $env:SYNAPSE_PRIVATE_NPM_REGISTRY } else { $RenderedPrivateRegistry }
  if ($privateRegistry -like '@@*@@') { $privateRegistry = '' }
  if (-not $privateRegistry) { Die 'no private @synapse registry configured; one-click bootstrap cannot install @synapse/*' }

  $artifactKey = Get-Platform
  Write-Log "platform: $artifactKey"

  $regionResolved = Get-Region
  $mirrorInfo = Resolve-ToolchainMirror $regionResolved

  $synapseHome = Get-SynapseHome
  $script:NpmGlobalPrefix = Join-Path $synapseHome 'npm-global'
  $managedNpmrc = Join-Path $synapseHome 'npmrc'

  # Fast path: existing Node satisfying engines.
  $useExisting = $false
  $existingNode = Get-Command node -ErrorAction SilentlyContinue
  if ($existingNode) {
    $cur = try { & node -p 'process.versions.node' } catch { '' }
    if ($cur -and (Test-NodeEngines $cur)) {
      Write-Log "using existing Node v$cur"
      $script:NodeExe = $existingNode.Source
      $script:NpmCmd = 'npm'
      $env:PATH = "$($script:NpmGlobalPrefix);$env:PATH"
      $useExisting = $true
    }
  }
  if (-not $useExisting) {
    Write-Log "bootstrapping Node $InstallerNodeVersion"
    Install-Node $artifactKey $mirrorInfo $regionResolved $synapseHome
  }

  # Third-party registry selection.
  $thirdParty = ''
  if ($PreferPrivateCache) { $thirdParty = $privateRegistry }
  elseif ($regionResolved -eq 'cn') { $thirdParty = if ($env:SYNAPSE_NPM_UPSTREAM_REGISTRY) { $env:SYNAPSE_NPM_UPSTREAM_REGISTRY } else { 'https://registry.npmmirror.com/' } }
  else { $thirdParty = if ($env:SYNAPSE_NPM_UPSTREAM_REGISTRY) { $env:SYNAPSE_NPM_UPSTREAM_REGISTRY } else { '' } }

  Set-Npmrc $privateRegistry $thirdParty $managedNpmrc
  Set-ToolchainMirror $mirrorInfo.P5
  # Persist the npm-global PREFIX ROOT — on Windows the npm global bin shims
  # (synapse-device.cmd etc.) live at the prefix root, not a bin/ subdir. When
  # we bootstrapped our own Node, also persist that Node dir so the shims'
  # node fallback resolves in a fresh terminal.
  Set-UserPath $script:NpmGlobalPrefix
  if (-not $useExisting -and $script:NodeDir) { Set-UserPath $script:NodeDir }

  $pkg = if ($Target -eq 'device') { '@synapse/device-runtime' } else { '@synapse/remote-agent-daemon' }
  $binName = if ($Target -eq 'device') { 'synapse-device.cmd' } else { 'synapse-remote-agent-daemon.cmd' }
  Install-SynapsePackage $pkg $privateRegistry $thirdParty $managedNpmrc
  $bin = Join-Path $script:NpmGlobalPrefix $binName

  if ($Target -eq 'device') { Invoke-Pair $bin $server $Code }
  else { Start-Daemon $bin $server $ApiKey }

  Write-Log 'Done.'
}

Main
