// Code generated by scripts/codegen/relay-policies.ts; DO NOT EDIT.
//
// Source of truth: packages/shared/src/access/policies/*.ts (Zod schemas).
// Regenerate with: npm run codegen:relay-policies

package runtimeauth

type FilesystemPolicy struct {
	Access       string   `json:"access"`
	PathPrefixes []string `json:"pathPrefixes"`
}

type CUAPolicy struct {
	Access string `json:"access"`
}

type BrowserPolicy struct {
	Action            string `json:"action"`
	ScopeType         string `json:"scopeType,omitempty"`
	Origin            string `json:"origin,omitempty"`
	Host              string `json:"host,omitempty"`
	RegistrableDomain string `json:"registrableDomain,omitempty"`
}

type CommandlinePolicy struct {
	Executor         string `json:"executor"`
	CommandMatchType string `json:"commandMatchType"`
	CommandText      string `json:"commandText,omitempty"`
	WorkingDirectory string `json:"workingDirectory,omitempty"`
}

type GrantPolicy struct {
	Capability  string             `json:"capability"`
	Filesystem  *FilesystemPolicy  `json:"filesystem,omitempty"`
	CUA         *CUAPolicy         `json:"cua,omitempty"`
	Browser     *BrowserPolicy     `json:"browser,omitempty"`
	Commandline *CommandlinePolicy `json:"commandline,omitempty"`
}
