#!/usr/bin/env bash
# Allocate 3 unused host ports in [15000, 15999] for a worktree staging stack.
# Writes PG_PORT, REDIS_PORT, NGINX_PORT into the given env file.
# Uses flock on a system-wide lock so concurrent worktrees don't race.

set -euo pipefail

ENV_FILE="${1:?Usage: allocate-staging-ports.sh <env-file>}"
LOCK_FILE="/tmp/synapse-staging-port-alloc.lock"
PORT_MIN=15000
PORT_MAX=15999

is_port_free() {
  local port="$1"
  if ss -lntH 2>/dev/null | awk '{print $4}' | grep -qE "[:.]${port}\$"; then
    return 1
  fi
  if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
    exec 3<&- 3>&-
    return 1
  fi
  return 0
}

pick_free_port() {
  local used_csv="${1:-}"
  local p
  for ((p = PORT_MIN; p <= PORT_MAX; p++)); do
    if [[ ",${used_csv}," == *",${p},"* ]]; then
      continue
    fi
    if is_port_free "$p"; then
      printf '%s' "$p"
      return 0
    fi
  done
  echo "ERROR: no free port in [${PORT_MIN},${PORT_MAX}]" >&2
  return 1
}

# Atomically acquire system lock so multiple worktrees don't claim the same port.
exec 9>"$LOCK_FILE"
flock 9

USED=""
PG_PORT=$(pick_free_port "$USED")
USED="${USED:+$USED,}${PG_PORT}"
REDIS_PORT=$(pick_free_port "$USED")
USED="${USED:+$USED,}${REDIS_PORT}"
NGINX_PORT=$(pick_free_port "$USED")

mkdir -p "$(dirname "$ENV_FILE")"

generate_secret() {
  openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

POSTGRES_PASSWORD=$(generate_secret)
REDIS_PASSWORD=$(generate_secret)
JWT_SECRET=$(generate_secret)
JWT_REFRESH_SECRET=$(generate_secret)
APP_SECRET=$(generate_secret)
MCP_ENCRYPTION_KEY=$(generate_secret)

cat > "$ENV_FILE" <<EOF
# Auto-generated by allocate-staging-ports.sh — do NOT commit.
# Regenerate by deleting this file and re-running staging-env.sh.

PG_PORT=${PG_PORT}
REDIS_PORT=${REDIS_PORT}
NGINX_PORT=${NGINX_PORT}

POSTGRES_USER=synapse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=synapse_staging

REDIS_PASSWORD=${REDIS_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
APP_SECRET=${APP_SECRET}
MCP_ENCRYPTION_KEY=${MCP_ENCRYPTION_KEY}

PLATFORM_ADMIN_EMAILS=staging-admin@synapse.test
MEMORY_ALLOW_RUNTIME_MODEL_DOWNLOAD=false
EOF

chmod 600 "$ENV_FILE"
echo "Allocated staging ports: PG=${PG_PORT} REDIS=${REDIS_PORT} NGINX=${NGINX_PORT}"
echo "Wrote ${ENV_FILE}"
