FROM node:20-alpine AS builder
WORKDIR /app

COPY packages/shared /app/packages/shared
WORKDIR /app/packages/shared
RUN npm install
RUN npm run build

COPY packages/web-next /app/packages/web-next
WORKDIR /app/packages/web-next
RUN npm ci
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/packages/web-next/.next ./.next
COPY --from=builder /app/packages/web-next/public ./public
COPY --from=builder /app/packages/web-next/node_modules ./node_modules
COPY --from=builder /app/packages/web-next/package.json ./
EXPOSE 3000
CMD ["npx", "next", "start", "-p", "3000"]
