//! SQLite-backed index with FTS5 virtual table for content search and Tika
//! pipeline integration for rich-format documents (PDF / DOC(X) / PPT(X) /
//! XLS(X) / RTF / HTML).

use std::fs;
use std::io::Read;
use std::path::Path;

use rusqlite::{params, Connection, OptionalExtension};
use walkdir::WalkDir;

use crate::blobs::open_nofollow;
use crate::path::{canonical, host_path, under_prefix};
use crate::rpc::{IndexErrors, IndexRebuildResult, IndexStatusResult, RpcError};

const INDEX_CONTENT_CAP: u64 = 1024 * 1024;

pub struct IndexStore {
    pub conn: Connection,
    pub ignore_segments: Vec<String>,
    pub last_indexed_at: Option<String>,
    pub extract_failed: i64,
    pub tika_endpoint: Option<String>,
    /// Max bytes sent to Tika for a single rich-format file. Office Open
    /// XML containers (PPTX/DOCX/XLSX) put their central directory at the
    /// tail of the ZIP, so truncating the payload almost always breaks
    /// parsing. Default 50 MiB; operator can raise via --max-extract-bytes.
    pub max_extract_bytes: u64,
}

impl IndexStore {
    pub fn open(work_dir: &Path, ignore: &str) -> Result<Self, RpcError> {
        Self::open_with_tika(work_dir, ignore, None, 50 * 1024 * 1024)
    }

    pub fn open_with_tika(
        work_dir: &Path,
        ignore: &str,
        tika_endpoint: Option<&str>,
        max_extract_bytes: u64,
    ) -> Result<Self, RpcError> {
        let db_path = work_dir.join("index.sqlite");
        // Schema migration via PRAGMA user_version. Bumping SCHEMA_VERSION
        // forces a clean rebuild — the index can always be regenerated by
        // scanning the VFS, so destructive reset is the safest answer for
        // older sidecar versions that wrote a different `docs` shape.
        const SCHEMA_VERSION: i32 = 1;
        let needs_reset = {
            // Open without WAL pragma first so we can inspect user_version
            // cheaply. If the file is missing entirely the open creates a
            // fresh empty db and user_version is 0 (matches "needs reset"
            // → CREATE TABLE IF NOT EXISTS will run anyway).
            if db_path.exists() {
                let probe = Connection::open(&db_path)?;
                let cur: i32 = probe
                    .query_row("PRAGMA user_version", [], |r| r.get(0))
                    .unwrap_or(0);
                drop(probe);
                cur != SCHEMA_VERSION
            } else {
                false
            }
        };
        if needs_reset {
            // Drop the index sidecar files cleanly. WAL / SHM may exist
            // from prior runs; remove all three so the next open is fresh.
            for suffix in ["", "-wal", "-shm"] {
                let p = work_dir.join(format!("index.sqlite{suffix}"));
                let _ = std::fs::remove_file(&p);
            }
        }
        let db = Connection::open(&db_path)?;
        db.execute_batch(&format!(
            "PRAGMA journal_mode = WAL;
             PRAGMA user_version = {SCHEMA_VERSION};
             CREATE TABLE IF NOT EXISTS docs (
                rowid INTEGER PRIMARY KEY,
                path TEXT UNIQUE NOT NULL,
                extension TEXT,
                mime TEXT,
                size INTEGER,
                mtime_ms INTEGER,
                source TEXT,
                indexed_at TEXT
             );
             CREATE VIRTUAL TABLE IF NOT EXISTS docs_fts USING fts5(
                content,
                tokenize='unicode61'
             );"
        ))?;
        let ignore_segments: Vec<String> = ignore
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
        Ok(Self {
            conn: db,
            ignore_segments,
            last_indexed_at: None,
            extract_failed: 0,
            tika_endpoint: tika_endpoint.map(|s| s.to_string()),
            max_extract_bytes,
        })
    }

    fn is_ignored(&self, rel: &Path) -> bool {
        rel.components().any(|c| {
            let s = c.as_os_str().to_string_lossy();
            self.ignore_segments.iter().any(|i| i == &s)
        })
    }

    pub fn rebuild(
        &mut self,
        root: &Path,
        subtree: Option<&str>,
    ) -> Result<IndexRebuildResult, RpcError> {
        let sub = subtree.unwrap_or("/");
        let sub_canon = canonical(sub)?;
        let host_sub = host_path(root, &sub_canon)?;
        if !host_sub.exists() {
            self.delete_subtree(&sub_canon)?;
            self.last_indexed_at = Some(now_stamp());
            return Ok(IndexRebuildResult { task_id: "rebuild-noop".into() });
        }
        self.delete_subtree(&sub_canon)?;
        let ignores = self.ignore_segments.clone();
        for entry in WalkDir::new(&host_sub).follow_links(false).into_iter().filter_map(|e| e.ok()) {
            let p = entry.path();
            let rel = match p.strip_prefix(root) { Ok(r) => r, Err(_) => continue };
            if rel.components().any(|c| ignores.iter().any(|i| *i == c.as_os_str().to_string_lossy())) {
                continue;
            }
            if !entry.file_type().is_file() { continue; }
            // Build the VFS path by joining components with '/'. NEVER
            // silently convert '\' to '/' — POSIX allows a literal
            // backslash in a filename, so a real file named
            // `public\leak.txt` would otherwise be indexed as the VFS
            // path `/public/leak.txt` and bypass the runtime's per-
            // prefix grant filter on indexed search (the search would
            // post-filter and decide it really lives under `/public`).
            // Push raw segment strings, then re-run `canonical()` to
            // enforce the same VFS rules as every other path argument:
            // reject backslash, drive-letter prefix, colon, DOS-reserved
            // names, internal namespace. Anything canonical() refuses
            // gets silently dropped from the index — better to under-
            // index a weird filename than to index it under a path
            // that the runtime would later mis-attribute.
            let mut buf = String::from("/");
            let mut malformed = false;
            let mut first = true;
            for c in rel.components() {
                let s = match c.as_os_str().to_str() {
                    Some(s) => s,
                    None => { malformed = true; break; }
                };
                if !first { buf.push('/'); }
                first = false;
                buf.push_str(s);
            }
            if malformed { continue; }
            let canon_path = match canonical(&buf) {
                Ok(s) => s,
                Err(_) => continue,
            };
            self.upsert_host(p, &canon_path)?;
        }
        self.last_indexed_at = Some(now_stamp());
        Ok(IndexRebuildResult { task_id: "rebuild-1".into() })
    }

    fn delete_subtree(&mut self, canon: &str) -> Result<(), RpcError> {
        let victims: Vec<(i64, String)> = {
            let mut stmt = self.conn.prepare("SELECT rowid, path FROM docs")?;
            let rows = stmt.query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, String>(1)?)))?;
            let mut out = Vec::new();
            for row in rows {
                let (rid, p) = row?;
                if canon == "/" || under_prefix(&p, canon) {
                    out.push((rid, p));
                }
            }
            out
        };
        let tx = self.conn.transaction()?;
        for (rid, _p) in victims {
            tx.execute("DELETE FROM docs WHERE rowid = ?", params![rid])?;
            tx.execute("DELETE FROM docs_fts WHERE rowid = ?", params![rid])?;
        }
        tx.commit()?;
        Ok(())
    }

    pub fn upsert(&mut self, root: &Path, path: &str) -> Result<(), RpcError> {
        let canon = canonical(path)?;
        let host = host_path(root, &canon)?;
        if !host.exists() {
            self.remove(&canon)?;
            return Ok(());
        }
        self.upsert_host(&host, &canon)
    }

    fn upsert_host(&mut self, host: &Path, canon_path: &str) -> Result<(), RpcError> {
        // symlink_metadata (not metadata) so a symlink at the final
        // component is reported as kind=symlink, not its target's kind.
        // A symlink could legitimately exist at a user-VFS path, but its
        // target may live outside root or in an unauthorized subtree —
        // indexing the target's bytes would silently leak content.
        // Strip any existing doc for this path and skip extraction.
        let meta = match fs::symlink_metadata(host) {
            Ok(m) => m,
            Err(_) => {
                // Vanished between RPC and here — remove if present.
                self.remove(canon_path)?;
                return Ok(());
            }
        };
        if meta.file_type().is_symlink() {
            self.remove(canon_path)?;
            return Ok(());
        }
        if !meta.is_file() {
            self.remove(canon_path)?;
            return Ok(());
        }
        let size = meta.len() as i64;
        let mtime_ms = meta
            .modified()
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_millis() as i64)
            .unwrap_or(0);
        let ext = host
            .extension()
            .map(|e| e.to_string_lossy().to_string())
            .unwrap_or_default();
        let mime = mime_guess::from_path(host)
            .first_or_octet_stream()
            .essence_str()
            .to_string();
        let (content, source) = self.extract_for_index(host, &mime, &ext, meta.len());
        let indexed_at = now_stamp();
        let tx = self.conn.transaction()?;
        tx.execute(
            "INSERT INTO docs(path, extension, mime, size, mtime_ms, source, indexed_at) VALUES (?, ?, ?, ?, ?, ?, ?)
             ON CONFLICT(path) DO UPDATE SET extension=excluded.extension, mime=excluded.mime, size=excluded.size, mtime_ms=excluded.mtime_ms, source=excluded.source, indexed_at=excluded.indexed_at",
            params![canon_path, ext, mime, size, mtime_ms, source, indexed_at],
        )?;
        let rowid: i64 = tx.query_row(
            "SELECT rowid FROM docs WHERE path = ?",
            params![canon_path], |r| r.get(0),
        )?;
        tx.execute("DELETE FROM docs_fts WHERE rowid = ?", params![rowid])?;
        if !content.is_empty() {
            tx.execute(
                "INSERT INTO docs_fts(rowid, content) VALUES (?, ?)",
                params![rowid, content],
            )?;
        }
        tx.commit()?;
        Ok(())
    }

    fn extract_for_index(
        &mut self, host: &Path, mime: &str, ext: &str, size: u64,
    ) -> (String, &'static str) {
        // Rich-format MIME + Tika configured → call Tika. Send the FULL
        // file (bounded by --max-extract-bytes, default 50 MiB) — Office
        // Open XML (PPTX/DOCX/XLSX) and EPUB are ZIP containers whose
        // central directory is at the file tail. Truncating mid-file
        // produces invalid ZIPs that Tika rejects.
        if is_rich_format(mime, ext) {
            if size > self.max_extract_bytes {
                // Oversize rich-format files: skip extraction rather than
                // send a guaranteed-broken truncation.
                self.extract_failed += 1;
                return (String::new(), "extract_oversize");
            }
            if let Some(endpoint) = self.tika_endpoint.clone() {
                match tika_extract_blocking(&endpoint, host, mime, self.max_extract_bytes) {
                    Ok(text) => return (text, "rich"),
                    Err(_) => {
                        self.extract_failed += 1;
                        return (String::new(), "extract_failed");
                    }
                }
            }
            // No Tika endpoint → mark and skip content.
            self.extract_failed += 1;
            return (String::new(), "no_tika");
        }
        // Plain text path: cap-bounded stream-read.
        if size > INDEX_CONTENT_CAP {
            self.extract_failed += 1;
            return (String::new(), "too_large");
        }
        let mut buf = Vec::with_capacity(size as usize);
        // O_NOFOLLOW on the plaintext read path. upsert_host already
        // symlink_metadata-checked, but a final-component symlink swap
        // between that and this open would otherwise let us read a
        // pointed-to target.
        let read_result = (|| -> Result<(), String> {
            let f = open_nofollow(host).map_err(|e| format!("{e}"))?;
            f.take(INDEX_CONTENT_CAP)
                .read_to_end(&mut buf)
                .map(|_| ())
                .map_err(|e| format!("{e}"))
        })();
        if read_result.is_err() {
            self.extract_failed += 1;
            return (String::new(), "read_failed");
        }
        match String::from_utf8(buf) {
            Ok(s) => (s, "text"),
            Err(_) => {
                self.extract_failed += 1;
                (String::new(), "binary")
            }
        }
    }

    pub fn remove(&mut self, path: &str) -> Result<(), RpcError> {
        let canon = canonical(path)?;
        let rowid: Option<i64> = self.conn.query_row(
            "SELECT rowid FROM docs WHERE path = ?",
            params![canon], |r| r.get(0),
        ).optional()?;
        if let Some(rid) = rowid {
            self.conn.execute("DELETE FROM docs WHERE rowid = ?", params![rid])?;
            self.conn.execute("DELETE FROM docs_fts WHERE rowid = ?", params![rid])?;
        }
        Ok(())
    }

    pub fn status(&self, subtree: &str) -> Result<IndexStatusResult, RpcError> {
        compute_status(&self.conn, subtree)
    }

    /// FTS5-backed content search. Emits up to `limit` hits under
    /// `allowed_prefixes` ordered by bm25.
    ///
    /// **Pagination correctness.** We CANNOT push `path LIKE ...` into the
    /// SQL — paths may legitimately contain `_` or `%`, which SQLite's
    /// LIKE treats as wildcards (corrupts the boundary semantics
    /// `under_prefix` guarantees in Rust). Instead we page through FTS
    /// results in batches and apply the boundary-aware filter in Rust
    /// until we've collected `limit` authorized hits — or hit a sane
    /// scan ceiling so a pathological query with millions of unauthorized
    /// matches can't tie up the helper indefinitely.
    pub fn fts_search<F: FnMut(&str, f64, &str)>(
        &self,
        query: &str,
        allowed_prefixes: &[String],
        limit: usize,
        mut hit: F,
    ) -> Result<(), RpcError> {
        if limit == 0 {
            return Ok(());
        }
        let escaped = fts5_escape(query);
        const MAX_SCAN: usize = 50_000;
        const PAGE_SIZE: i64 = 256;
        let mut offset: i64 = 0;
        let mut emitted = 0usize;
        let mut scanned = 0usize;
        let mut stmt = self.conn.prepare(
            "SELECT docs.path, bm25(docs_fts) AS score,
                    snippet(docs_fts, 0, '', '', '...', 32) AS snip
             FROM docs_fts JOIN docs ON docs.rowid = docs_fts.rowid
             WHERE docs_fts MATCH ?
             ORDER BY score
             LIMIT ? OFFSET ?",
        )?;
        loop {
            let page: Vec<(String, f64, String)> = {
                let rows = stmt.query_map(
                    params![escaped, PAGE_SIZE, offset],
                    |r| {
                        Ok((
                            r.get::<_, String>(0)?,
                            r.get::<_, f64>(1)?,
                            r.get::<_, String>(2)?,
                        ))
                    },
                )?;
                let mut out = Vec::new();
                for row in rows {
                    out.push(row?);
                }
                out
            };
            if page.is_empty() {
                break;
            }
            offset += page.len() as i64;
            for (p, score, snip) in page {
                scanned += 1;
                if !allowed_prefixes.is_empty()
                    && !allowed_prefixes.iter().any(|pref| under_prefix(&p, pref))
                {
                    continue;
                }
                hit(&p, -score, &snip);
                emitted += 1;
                if emitted >= limit {
                    return Ok(());
                }
            }
            if scanned >= MAX_SCAN {
                break;
            }
        }
        Ok(())
    }

    /// All paths under allowed_prefixes — used by search_path nucleo fuzzy.
    pub fn iter_paths<F: FnMut(&str)>(
        &self, allowed_prefixes: &[String], mut visit: F,
    ) -> Result<(), RpcError> {
        let mut stmt = self.conn.prepare("SELECT path FROM docs")?;
        let rows = stmt.query_map([], |r| r.get::<_, String>(0))?;
        for r in rows {
            let p = r?;
            if allowed_prefixes.is_empty()
                || allowed_prefixes.iter().any(|pref| under_prefix(&p, pref))
            { visit(&p); }
        }
        Ok(())
    }
}

fn now_stamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let s = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs();
    format!("ts:{s}")
}

pub fn allowed(path: &str, prefixes: &[String]) -> bool {
    if prefixes.is_empty() { return false; }
    prefixes.iter().any(|p| under_prefix(path, p))
}

fn is_rich_format(mime: &str, ext: &str) -> bool {
    let m = mime.to_ascii_lowercase();
    let e = ext.to_ascii_lowercase();
    matches!(m.as_str(),
        "application/pdf"
        | "application/msword"
        | "application/vnd.ms-excel"
        | "application/vnd.ms-powerpoint"
        | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        | "application/vnd.openxmlformats-officedocument.presentationml.presentation"
        | "application/rtf" | "text/rtf"
        | "text/html" | "application/xhtml+xml"
        | "application/epub+zip"
    ) || matches!(e.as_str(),
        "pdf" | "doc" | "docx" | "ppt" | "pptx" | "xls" | "xlsx"
        | "rtf" | "html" | "htm" | "epub" | "odt" | "ods" | "odp"
    )
}

fn fts5_escape(q: &str) -> String {
    let trimmed = q.trim();
    if trimmed.is_empty() { return "\"\"".into(); }
    trimmed.split_whitespace().map(|tok| {
        let esc = tok.replace('"', "\"\"");
        format!("\"{esc}\"")
    }).collect::<Vec<_>>().join(" ")
}

/// Synchronous Tika HTTP via `ureq`. Index-time upserts run on the tokio
/// dispatch thread, so we MUST NOT create a tokio runtime here (would
/// panic "Cannot start a runtime from within a runtime"). `ureq` is a
/// dependency-light blocking client that avoids the issue entirely; the
/// user-facing fs.extract.text path keeps the async reqwest client.
fn tika_extract_blocking(
    endpoint: &str,
    host: &Path,
    mime: &str,
    max_bytes: u64,
) -> Result<String, String> {
    let url = format!("{}/tika", endpoint.trim_end_matches('/'));
    // symlink_metadata + O_NOFOLLOW open: same anti-symlink-swap
    // protection as the plaintext index path. If host is a symlink, error
    // out so the caller marks extract_failed.
    let meta = std::fs::symlink_metadata(host).map_err(|e| e.to_string())?;
    if meta.file_type().is_symlink() {
        return Err("symlink_not_followed".to_string());
    }
    let cap = max_bytes.min(meta.len()) as usize;
    let file = open_nofollow(host).map_err(|e| e.to_string())?;
    let mut buf = Vec::with_capacity(cap.min(64 * 1024));
    file.take(cap as u64)
        .read_to_end(&mut buf)
        .map_err(|e| e.to_string())?;
    let agent = ureq::AgentBuilder::new()
        .timeout(std::time::Duration::from_secs(30))
        .build();
    let resp = agent
        .put(&url)
        .set("Accept", "text/plain")
        .set("Content-Type", mime)
        .send_bytes(&buf)
        .map_err(|e| format!("tika_request: {e}"))?;
    if resp.status() < 200 || resp.status() >= 300 {
        return Err(format!("tika_http_{}", resp.status()));
    }
    resp.into_string().map_err(|e| format!("tika_body: {e}"))
}

/// Open a fresh **read-only** SQLite handle on the index. Used by
/// `fs.index.status` so a status query can compute counts WITHOUT
/// contending with a rebuild's `IndexStore` mutex. The previous design
/// (`try_lock` + `doc_count_pending` stub fallback) leaked the busy
/// state across subtrees: a /public-only caller could see
/// `doc_count_pending:true` whenever ANY rebuild — including a sibling
/// /secret one — held the index mutex, even after the runtime stripped
/// the unauthorized `rebuild_task` field. WAL mode allows concurrent
/// readers without writer contention, so a separate handle gets the
/// real (possibly mid-rebuild stale) counts without the side channel.
pub fn open_status_conn(work_dir: &Path) -> Result<Connection, RpcError> {
    let db_path = work_dir.join("index.sqlite");
    if !db_path.exists() {
        return Err(RpcError::Internal("index_db_missing".into()));
    }
    let c = Connection::open_with_flags(
        &db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY
            | rusqlite::OpenFlags::SQLITE_OPEN_URI
            | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )?;
    // WAL readers must not try to switch journal mode; do nothing here.
    Ok(c)
}

/// Compute index status from a SQLite handle. Factored out so both the
/// owning `IndexStore::status` and the read-only fallback in
/// `fs.index.status` can share the same SQL.
pub fn compute_status(conn: &Connection, subtree: &str) -> Result<IndexStatusResult, RpcError> {
    let canon = canonical(subtree)?;
    // Per-subtree aggregation: returning the global IndexStore counters
    // would let a /public-only caller observe /secret's indexing activity
    // (failure count, last-indexed timestamp).
    //
    // `source` is recorded on every doc row by upsert_host; values
    // that count as a failed extraction are gathered here. Successful
    // extractions are "text" | "rich".
    const FAILED_SOURCES: &[&str] = &[
        "extract_failed",
        "extract_oversize",
        "no_tika",
        "too_large",
        "binary",
        "read_failed",
        "symlink_skipped",
    ];
    let mut stmt = conn.prepare("SELECT path, source, indexed_at FROM docs")?;
    let rows = stmt.query_map([], |r| {
        Ok((
            r.get::<_, String>(0)?,
            r.get::<_, Option<String>>(1)?,
            r.get::<_, Option<String>>(2)?,
        ))
    })?;
    let mut count: i64 = 0;
    let mut extract_failed: i64 = 0;
    let mut last_indexed_at: Option<String> = None;
    for r in rows {
        let (path, source, indexed_at) = r?;
        if canon != "/" && !under_prefix(&path, &canon) {
            continue;
        }
        count += 1;
        if let Some(s) = &source {
            if FAILED_SOURCES.iter().any(|f| *f == s.as_str()) {
                extract_failed += 1;
            }
        }
        if let Some(ts) = indexed_at {
            match &last_indexed_at {
                Some(cur) if cur.as_str() >= ts.as_str() => {}
                _ => last_indexed_at = Some(ts),
            }
        }
    }
    Ok(IndexStatusResult {
        subtree: canon,
        last_indexed_at,
        doc_count: count,
        queue_depth: 0,
        errors: IndexErrors {
            extract_failed,
            watcher_starved: 0,
        },
    })
}
