#!/usr/bin/env node
// Refresh chrome-devtools-mcp static input schemas. Spawn the pinned sidecar,
// fetch tools/list, write the canonical input schemas back to
// `src/builtins/chrome-devtools-mcp.static-input-schemas.json` so the
// provider's describeExposures() reports input shapes that match what the
// running sidecar actually accepts.
//
// Run manually when bumping PINNED_VERSION. Plan §Phase 5, clarification #19.

import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"
import { PINNED_VERSION } from "../src/builtins/chrome-devtools-mcp.js"
import { startMcpStdioSidecar } from "../src/mcp-stdio-sidecar.js"

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(
  here,
  "..",
  "src",
  "builtins",
  "chrome-devtools-mcp.static-input-schemas.json"
)

async function main() {
  const handle = await startMcpStdioSidecar({
    command: "npx",
    args: [
      "-y",
      `chrome-devtools-mcp@${PINNED_VERSION}`,
      "--headless=true",
      "--isolated",
      "--no-usage-statistics",
      "--no-performance-crux",
      "--experimentalStructuredContent",
    ],
    env: {
      ...process.env,
      CHROME_DEVTOOLS_MCP_NO_UPDATE_CHECKS: "1",
    },
  })
  try {
    const tools = await handle.client.listTools()
    const schemas: Record<string, unknown> = {}
    for (const tool of tools.tools) {
      if (tool.inputSchema) schemas[tool.name] = tool.inputSchema
    }
    const dump = {
      _comment:
        "Static input-schema fallback for chrome-devtools-mcp tools. Generated by scripts/refresh-browser-tool-schemas.ts.",
      _pinnedVersion: PINNED_VERSION,
      schemas,
    }
    writeFileSync(OUT, JSON.stringify(dump, null, 2) + "\n")
    console.log(`wrote ${Object.keys(schemas).length} schemas to ${OUT}`)
  } finally {
    await handle.client.close()
    await handle.exited
  }
}

void main().catch((err) => {
  console.error("refresh failed:", err)
  process.exit(1)
})
